name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore "Marke-se api.csproj"

      - name: Build
        run: dotnet publish "Marke-se api.csproj" -c:Release --no-restore

      - name: Publish
        run: dotnet publish "Marke-se api.csproj" --configuration Release --no-build --output ./published-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./published-app/wwwroot
